export const metadata = {
  title: "Terms of Service — throws.gg",
  description: "Terms of Service for throws.gg virtual horse racing platform.",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12 text-white/70 text-sm leading-relaxed space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-white mb-1">Terms of Service</h1>
        <p className="text-white/30 text-xs">Last updated: April 2026</p>
      </div>

      <p>
        By accessing or using throws.gg (&quot;the Platform&quot;, &quot;we&quot;, &quot;us&quot;), you agree to be bound by these
        Terms of Service. If you do not agree, do not use the Platform.
      </p>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">1. Eligibility</h2>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>You must be at least 18 years old (or the legal gambling age in your jurisdiction, whichever is higher) to use the Platform.</li>
          <li>You are solely responsible for determining whether online gambling is legal in your jurisdiction. We do not provide legal advice.</li>
          <li>Users from jurisdictions where online gambling is prohibited must not use the Platform.</li>
          <li>You may only hold one account. Multiple accounts will be terminated and balances forfeited.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">2. The Platform</h2>
        <p>
          throws.gg offers virtual horse racing — a simulated betting product.
          All races are generated by a deterministic algorithm, not based on real-world horse racing events.
          Race outcomes are provably fair and verifiable using HMAC-SHA256 cryptographic seeds.
        </p>
        <p>
          We operate as the house. Odds are fixed at the time of bet placement. The house edge is built into the odds
          via an overround. By placing bets, you acknowledge that the house has a mathematical advantage over time.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">3. Deposits &amp; Withdrawals</h2>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Deposits are accepted in USDC and SOL on the Solana blockchain via Privy embedded wallets.</li>
          <li>Your balance is denominated in USD. Crypto deposits are converted to USD at the current market rate at the time of deposit.</li>
          <li>Minimum deposit: $1 USD. Minimum withdrawal: $5 USD.</li>
          <li>Withdrawals are processed in USDC on Solana. Withdrawals under $500 are processed automatically. Larger withdrawals may require manual review and take up to 24 hours.</li>
          <li>You are responsible for providing a valid Solana wallet address. We are not liable for funds sent to an incorrect address.</li>
          <li>We reserve the right to request identity verification before processing withdrawals if suspicious activity is detected.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">4. Betting Rules</h2>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>All bets are final once placed unless cancelled during the betting window before gates close.</li>
          <li>Odds are locked at the time of bet placement. Subsequent odds changes do not affect existing bets.</li>
          <li>Maximum bet limits apply and may vary based on current bankroll and horse liability.</li>
          <li>Winning bets are credited automatically to your balance upon race settlement.</li>
          <li>In the event of a system error or malfunction, we reserve the right to void affected bets and refund stakes.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">5. Provably Fair</h2>
        <p>
          Every race uses HMAC-SHA256 cryptographic seeds. Before betting opens, we publish a hash of the server seed.
          After the race, we reveal the server seed so you can independently verify that the race outcome was determined
          before any bets were placed. Full verification is available on the Verify page.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">6. Prohibited Conduct</h2>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Using automated tools, bots, or scripts to place bets or gain an unfair advantage.</li>
          <li>Exploiting bugs, glitches, or errors in the Platform. Users who discover vulnerabilities must report them immediately.</li>
          <li>Colluding with other users to manipulate outcomes or exploit the referral system.</li>
          <li>Using the Platform for money laundering, fraud, or any illegal activity.</li>
          <li>Creating multiple accounts to circumvent limits or claim bonuses multiple times.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">7. Account Suspension &amp; Termination</h2>
        <p>
          We reserve the right to suspend or terminate accounts at our discretion, including but not limited to:
          violations of these Terms, suspected fraud or abuse, regulatory requirements, or at your request (self-exclusion).
          Upon termination, remaining balances will be returned to the user&apos;s wallet address minus any pending obligations,
          unless the account was terminated for fraud.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">8. Limitation of Liability</h2>
        <p>
          The Platform is provided &quot;as is&quot; without warranties of any kind. We are not liable for: losses from gambling activity,
          blockchain network delays or failures, wallet provider issues, force majeure events, or any indirect, incidental,
          or consequential damages arising from your use of the Platform.
        </p>
        <p>
          Our total liability is limited to the balance in your account at the time of the claim.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">9. Responsible Gambling</h2>
        <p>
          We are committed to promoting responsible gambling. Please see our{" "}
          <a href="/responsible-gambling" className="text-violet underline hover:text-violet/80">Responsible Gambling</a>{" "}
          page for tools and resources, including self-exclusion and deposit limits.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">10. Changes to Terms</h2>
        <p>
          We may update these Terms at any time. Continued use of the Platform after changes constitutes acceptance.
          Material changes will be communicated via the Platform.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">11. Contact</h2>
        <p>
          For questions about these Terms, contact us at{" "}
          <a href="mailto:support@throws.gg" className="text-violet underline hover:text-violet/80">support@throws.gg</a>.
        </p>
      </section>
    </div>
  );
}
