-- ============================================
-- 028_rakeback.sql
-- Rakeback — tiered on users.total_wagered (lifetime).
-- Accrues on every bet settle (won OR lost — it's stake-based, not outcome-based).
-- Accumulates in users.rakeback_claimable until the user clicks Claim.
-- Claim credits directly to users.balance (cash) — no wagering requirement.
--
-- Why direct-to-cash is safe: rakeback can only be generated by real wagering,
-- which is already taxed by the house edge. A farmer depositing $100 loses $9
-- to edge and gets $0.45 back (5% of edge, Bronze tier). Self-capping.
--
-- Tier ladder (5 tiers, matches the VIP progression in feedback_vip_rakeback.md):
--   $0–$500       Bronze     5% of edge   (≈0.45% of wager at 9.09% edge)
--   $500–$5K      Silver    10% of edge   (≈0.91%)
--   $5K–$25K      Gold      15% of edge   (≈1.36%)
--   $25K–$100K    Platinum  20% of edge   (≈1.82%)
--   $100K+        Diamond   25% of edge   (≈2.27%)
--
-- EDGE_RATE = 0.0909 matches current OVERROUND = 1.10 (lib/racing/odds-engine.ts).
-- If OVERROUND changes, update EDGE_RATE in accrue_rakeback() to match.
--
-- Safe to re-run (IF NOT EXISTS / CREATE OR REPLACE).
-- ============================================

-- --------------------------------------------
-- SCHEMA
-- --------------------------------------------
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS rakeback_claimable NUMERIC(18, 8) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rakeback_lifetime  NUMERIC(18, 8) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_rakeback_claim_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_rakeback_nudge_at TIMESTAMPTZ;

-- Ledger of every accrual. Lets us audit / reconcile / show a history.
-- Each row represents a rakeback credit tied to one settled bet.
CREATE TABLE IF NOT EXISTS rakeback_accruals (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  race_bet_id    UUID NOT NULL REFERENCES race_bets(id) ON DELETE CASCADE,
  stake          NUMERIC(18, 8) NOT NULL,
  edge_rate      NUMERIC(8, 6) NOT NULL,      -- snapshot of EDGE_RATE at accrual time
  tier           TEXT NOT NULL,                -- bronze / silver / gold / platinum / diamond
  tier_pct       NUMERIC(4, 2) NOT NULL,       -- 0.05 / 0.10 / 0.15 / 0.20 / 0.25
  amount         NUMERIC(18, 8) NOT NULL,      -- stake * edge_rate * tier_pct
  accrued_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  claimed_at     TIMESTAMPTZ,                  -- null = still in rakeback_claimable
  claim_batch_id UUID,                         -- groups rows claimed together
  UNIQUE (race_bet_id)                         -- one accrual per bet, hard stop on double-accrue
);

CREATE INDEX IF NOT EXISTS idx_rakeback_user_unclaimed
  ON rakeback_accruals (user_id) WHERE claimed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_rakeback_user_accrued
  ON rakeback_accruals (user_id, accrued_at DESC);

-- --------------------------------------------
-- TIER LOOKUP
-- --------------------------------------------
-- Returns (tier_name, tier_pct) for a given lifetime wagered amount.
-- Pure function — no side effects, callable from settle_race + status endpoint.
CREATE OR REPLACE FUNCTION rakeback_tier(p_total_wagered NUMERIC)
RETURNS TABLE (tier TEXT, tier_pct NUMERIC) AS $$
BEGIN
  IF p_total_wagered >= 100000 THEN
    RETURN QUERY SELECT 'diamond'::TEXT, 0.25::NUMERIC;
  ELSIF p_total_wagered >= 25000 THEN
    RETURN QUERY SELECT 'platinum'::TEXT, 0.20::NUMERIC;
  ELSIF p_total_wagered >= 5000 THEN
    RETURN QUERY SELECT 'gold'::TEXT, 0.15::NUMERIC;
  ELSIF p_total_wagered >= 500 THEN
    RETURN QUERY SELECT 'silver'::TEXT, 0.10::NUMERIC;
  ELSE
    RETURN QUERY SELECT 'bronze'::TEXT, 0.05::NUMERIC;
  END IF;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- --------------------------------------------
-- ACCRUE
-- --------------------------------------------
-- Called from settle_race once per bet. Writes the ledger row and bumps
-- users.rakeback_claimable. Idempotent via UNIQUE (race_bet_id) — if a
-- settle retries, the second accrual hits unique_violation and no-ops.
--
-- Uses the user's CURRENT total_wagered (including the bet just settled) to
-- choose the tier — matches the "live tier" UX.
CREATE OR REPLACE FUNCTION accrue_rakeback(
  p_user_id     UUID,
  p_race_bet_id UUID,
  p_stake       NUMERIC
) RETURNS NUMERIC AS $$
DECLARE
  v_edge_rate NUMERIC := 0.0909;  -- matches OVERROUND = 1.10
  v_total_wagered NUMERIC;
  v_tier_row RECORD;
  v_amount NUMERIC;
BEGIN
  IF p_stake IS NULL OR p_stake <= 0 THEN
    RETURN 0;
  END IF;

  SELECT total_wagered INTO v_total_wagered FROM users WHERE id = p_user_id;
  IF v_total_wagered IS NULL THEN
    RETURN 0;
  END IF;

  SELECT * INTO v_tier_row FROM rakeback_tier(v_total_wagered);
  v_amount := ROUND((p_stake * v_edge_rate * v_tier_row.tier_pct)::NUMERIC, 8);

  IF v_amount <= 0 THEN
    RETURN 0;
  END IF;

  -- Idempotent insert — if this bet already accrued, bail out silently.
  BEGIN
    INSERT INTO rakeback_accruals (
      user_id, race_bet_id, stake, edge_rate, tier, tier_pct, amount
    ) VALUES (
      p_user_id, p_race_bet_id, p_stake, v_edge_rate,
      v_tier_row.tier, v_tier_row.tier_pct, v_amount
    );
  EXCEPTION WHEN unique_violation THEN
    RETURN 0;
  END;

  UPDATE users
    SET rakeback_claimable = rakeback_claimable + v_amount
    WHERE id = p_user_id;

  RETURN v_amount;
END;
$$ LANGUAGE plpgsql;

-- --------------------------------------------
-- CLAIM
-- --------------------------------------------
-- Atomic. Drains rakeback_claimable to balance, stamps claimed_at on every
-- unclaimed accrual for this user, writes a 'bonus' transaction row, bumps
-- rakeback_lifetime. No minimum amount.
--
-- Returns the claimed amount (0 if nothing to claim). Idempotent-safe: two
-- concurrent calls will both see the same starting claimable, but FOR UPDATE
-- on the user row serialises them — one claims, the other sees 0.
CREATE OR REPLACE FUNCTION claim_rakeback(p_user_id UUID)
RETURNS NUMERIC AS $$
DECLARE
  v_claimable NUMERIC;
  v_new_balance NUMERIC;
  v_batch_id UUID := gen_random_uuid();
  v_user users%ROWTYPE;
BEGIN
  SELECT * INTO v_user FROM users WHERE id = p_user_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'user not found' USING ERRCODE = 'P0002';
  END IF;

  v_claimable := v_user.rakeback_claimable;

  IF v_claimable IS NULL OR v_claimable <= 0 THEN
    RETURN 0;
  END IF;

  v_new_balance := v_user.balance + v_claimable;

  UPDATE users SET
    balance                = v_new_balance,
    rakeback_claimable     = 0,
    rakeback_lifetime      = rakeback_lifetime + v_claimable,
    last_rakeback_claim_at = NOW(),
    updated_at             = NOW()
  WHERE id = p_user_id;

  -- Stamp the ledger so future claims only pick up new accruals.
  UPDATE rakeback_accruals
    SET claimed_at = NOW(), claim_batch_id = v_batch_id
    WHERE user_id = p_user_id AND claimed_at IS NULL;

  -- Audit trail. Uses 'bonus' type to match daily login bonus convention.
  INSERT INTO transactions (
    user_id, type, amount, balance_after, currency, status, confirmed_at, metadata
  ) VALUES (
    p_user_id,
    'bonus'::tx_type,
    v_claimable,
    v_new_balance,
    'USD',
    'confirmed',
    NOW(),
    jsonb_build_object(
      'source', 'rakeback_claim',
      'batch_id', v_batch_id
    )
  );

  RETURN v_claimable;
END;
$$ LANGUAGE plpgsql;

-- --------------------------------------------
-- SETTLE_RACE — hook in accrue_rakeback
-- --------------------------------------------
-- Rewrites settle_race from migration 021 to call accrue_rakeback on every
-- settled bet. Accrual happens AFTER the payout routing but BEFORE the race
-- house_profit calculation — so it's attributed to the right bet and the
-- admin reporting stays clean (rakeback is a liability, not a reduction of
-- house_profit at settle time; it settles when the user claims).
CREATE OR REPLACE FUNCTION settle_race(
  p_race_id UUID,
  p_winning_horse_id INT,
  p_server_seed TEXT
) RETURNS void AS $$
DECLARE
  bet RECORD;
  payout_amount NUMERIC;
  bet_result race_bet_status;
  horse_finish INT;
  v_bonus_ratio NUMERIC;
  v_cash_portion NUMERIC;
  v_bonus_portion NUMERIC;
  v_user users%ROWTYPE;
  v_config bonus_config%ROWTYPE;
  v_new_bonus NUMERIC;
  v_new_cash NUMERIC;
BEGIN
  UPDATE races SET
    status = 'settled',
    winning_horse_id = p_winning_horse_id,
    server_seed = p_server_seed,
    settled_at = NOW()
  WHERE id = p_race_id;

  SELECT * INTO v_config FROM bonus_config WHERE id = 1;

  FOR bet IN SELECT * FROM race_bets WHERE race_id = p_race_id AND status = 'pending' LOOP
    SELECT finish_position INTO horse_finish
    FROM race_entries
    WHERE race_id = p_race_id AND horse_id = bet.horse_id;

    IF bet.bet_type = 'win' AND horse_finish = 1 THEN
      bet_result := 'won';
      payout_amount := bet.amount * bet.locked_odds;
    ELSIF bet.bet_type = 'place' AND horse_finish <= 2 THEN
      bet_result := 'won';
      payout_amount := bet.amount * bet.locked_odds;
    ELSIF bet.bet_type = 'show' AND horse_finish <= 3 THEN
      bet_result := 'won';
      payout_amount := bet.amount * bet.locked_odds;
    ELSE
      bet_result := 'lost';
      payout_amount := 0;
    END IF;

    UPDATE race_bets SET
      status = bet_result,
      payout = payout_amount,
      settled_at = NOW()
    WHERE id = bet.id;

    IF payout_amount > 0 THEN
      v_bonus_ratio := CASE
        WHEN bet.amount > 0 THEN COALESCE(bet.from_bonus_amount, 0) / bet.amount
        ELSE 0
      END;

      v_bonus_portion := ROUND((payout_amount * v_bonus_ratio)::numeric, 8);
      v_cash_portion := payout_amount - v_bonus_portion;

      SELECT * INTO v_user FROM users WHERE id = bet.user_id FOR UPDATE;

      IF v_bonus_portion > 0 AND (v_user.bonus_expires_at IS NULL OR v_user.bonus_expires_at > NOW()) THEN
        v_new_bonus := v_user.bonus_balance + v_bonus_portion;
      ELSE
        v_new_bonus := v_user.bonus_balance;
        IF v_bonus_portion > 0 THEN
          v_cash_portion := v_cash_portion + v_bonus_portion;
        END IF;
      END IF;

      v_new_cash := v_user.balance + v_cash_portion;

      IF v_user.wagering_remaining = 0 AND v_new_bonus > 0 THEN
        v_new_cash := v_new_cash + v_new_bonus;
        v_new_bonus := 0;
      END IF;

      UPDATE users SET
        balance = v_new_cash,
        bonus_balance = v_new_bonus,
        updated_at = NOW()
      WHERE id = bet.user_id;

      INSERT INTO transactions (user_id, type, amount, balance_after, currency, status, confirmed_at, metadata)
      VALUES (
        bet.user_id,
        'payout'::tx_type,
        payout_amount,
        v_new_cash,
        'USD',
        'confirmed',
        NOW(),
        jsonb_build_object(
          'race_bet_id', bet.id,
          'to_cash', v_cash_portion,
          'to_bonus', v_bonus_portion,
          'bonus_ratio', v_bonus_ratio
        )
      );
    END IF;

    -- Accrue rakeback on every settled bet (won or lost) — it's stake-based.
    -- Uses the user's current total_wagered which place_race_bet_atomic already
    -- bumped at bet placement, so this tiers on up-to-date lifetime volume.
    -- Fire-and-forget (accrue_rakeback swallows its own errors via the
    -- unique_violation branch) — never block settlement on rakeback failure.
    BEGIN
      PERFORM accrue_rakeback(bet.user_id, bet.id, bet.amount);
    EXCEPTION WHEN OTHERS THEN
      NULL;
    END;

    UPDATE races SET
      total_payout = total_payout + payout_amount
    WHERE id = p_race_id;
  END LOOP;

  UPDATE races SET
    house_profit = total_bet_amount - total_payout
  WHERE id = p_race_id;
END;
$$ LANGUAGE plpgsql;
